### ISSUE TITLE
[BUG] can't exit streams 

### ISSUE THREAD

**Issue by berberix** [DATL4G/BurningSeries-Android#54]
Hi there, 
I'm facing a bug with this app:
Once I start a stream I can't go back, or close the stream anymore. The displayed back button is not reactive and even the back gestute/soft button won't have any functionality. 
I'm using adguard adblocker (as local VPN) and adguard VPN (in compatibility mode) on my device and with both deactivated, it seems to be working. Do you think you can fix this or will I have to keep my adblocker and VPN off? 

 - Device: OnePlus 10 Pro 
 - OS: Android 13 
 - Version: NE2213_11_C.30

My temporary is fix is to have your app on the exclusion list in adguard, but it would be highly appreciated if that would not be necessary

**Comment by DatL4g** [comment]
May be fixed already in the upcoming new version.

If not, it's not a problem of my app, and may be a false positive in your adblock.
Maybe even because of a DISALLOW_SCREEN_RECORDING flag I have to set as it's a requirement for F-Droid


Otherwise I don't see why a network configuration could block a in app navigation

**Comment by DatL4g** [comment]
Please check https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
