### ISSUE TITLE
[BUG] android constantly restarting system ui

### ISSUE THREAD

**Issue by Slluxx** [DATL4G/BurningSeries-Android#89]
Since multiple versions I have the issue that after starting a show using Chromecast, my phone screen goes black (which is intended I guess) and after a few seconds, there is a constant switch between black screen and my phones Homescreen (it's not the actual Homescreen. It looks like it's restarting the system ui but I don't get any of the usual notifications for it). I am unable to go back to the app or even close the app at all. Trying to open the settings menu from the power menu doesn't do anything. I can lock my screen but after unlocking it's back to this funky behaviour. The only way to use my phone again is by restarting it.

**Comment by DatL4g** [comment]
Since `6.0.0` the intended behavior while Chromecasting is to show the last frame before switching to the casting device.
If thats a black image then the screen will be black if it's not then there should be an image, however your device should not turn off.
If you tell me which device it is I can check my logs but I'm not sure if I have any since the app is not crashing.

Alternatively you can see the device log using `adb` with `adb logcat *:W`
https://developer.android.com/tools/logcat

**Comment by Slluxx** [comment]
Started the log capture, connected to chromecast and started an episode which needed unlocking. After that, my phone started its thing again, which now looked like it was going to sleep and woken up again over and over. I regained control over my phone after quiting the chromecast stream on my tv and my phone was in a locked state after that.
[log.txt](https://github.com/user-attachments/files/17137362/log.txt)

Edit:

It really is the systemui crashing

```
09-25 21:03:03.113  2330  2330 E AndroidRuntime: FATAL EXCEPTION: main
09-25 21:03:03.113  2330  2330 E AndroidRuntime: Process: com.android.systemui, PID: 2330
09-25 21:03:03.113  2330  2330 E AndroidRuntime: java.lang.ArithmeticException: divide by zero
09-25 21:03:03.113  2330  2330 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.GetValuePolum
```

My phone is a Redmi Note 10 Pro running android 14

**Comment by Slluxx** [comment]
The problem continues to exist after the latest release

**Comment by DatL4g** [comment]
It's a system bug by your manufacturer, nothing I can do

**Comment by Slluxx** [comment]
This is the only app this happens in and the app worked previously just fine. You changed something and now blame my manufacturer? Crazy.

**Comment by DatL4g** [comment]
Stop being bitchy.

All I did was updating the dependencies, I'm not gonna roll them back or anything, which includes other bugs.

It is in fact a known Xiaomi bug, since they mess with casting features.

Additionally I'm not obligated to fix anything and especially not for special and cheap manufacturers.

Either fix it yourself, since you own such a device or stop complaining when I'm not able or willing to fix it.
